name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight (UTC)
  workflow_dispatch:      # Allows manual runs
permissions:
  contents: write        # Needed to commit changes
jobs:
  update-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Automatic token (no setup needed)
          # Customize your metrics here (see docs for options)
          config: >
            {
              "template": "classic",
              "plugin_lines": true,
              "plugin_languages": true
            }
      - name: Commit changes
        run: |
          git config --global user.name "NicoleKaldus"
          git config --global user.email "nkaldus@gmail.com"
          git add metrics/
          git commit -m "Update metrics"
          git push
